// brand-models.js — per-brand model-line catalog for the listing form.
// When a seller picks a brand, post.js fills the #pModel datalist from this map
// (most-iconic models first). It's a datalist, so a seller can pick from the list
// OR type a model that isn't here (rare references, new releases).
// Keys MUST match the <option> values in #pBrand exactly.
// Built + fact-checked brand-by-brand; safe to extend by hand.
window.BRAND_MODELS = {
  "Rolex": ["Submariner","Datejust","Daytona","GMT-Master II","Day-Date","Oyster Perpetual","Explorer","Sea-Dweller","Yacht-Master","Sky-Dweller","Explorer II","Air-King","Deepsea","Milgauss","Yacht-Master II","GMT-Master","Turn-O-Graph","Oyster Perpetual Date","Cellini","Perpetual 1908","Land-Dweller"],
  "Patek Philippe": ["Nautilus","Calatrava","Aquanaut","Grand Complications","Complications","Golden Ellipse","Gondolo","Cubitus","Twenty~4","Pocket Watches"],
  "Audemars Piguet": ["Royal Oak","Royal Oak Offshore","Royal Oak Concept","Code 11.59","Jules Audemars","Millenary"],
  "Richard Mille": ["RM 011","RM 035","RM 055","RM 010","RM 030","RM 027","RM 056","RM 050","RM 052","RM 07-01","RM 025","RM 019","RM 033","RM 037","RM 007","RM 016","RM 039","RM 060","RM 065","RM 067","RM 070","RM 071","RM 029","RM 005","RM 001"],
  "Vacheron Constantin": ["Overseas","Patrimony","Traditionnelle","Métiers d'Art","Fifty Six","Historiques","Malte","Égérie","Les Cabinotiers","Quai de l'Île","American 1921","Harmony"],
  "A. Lange & Söhne": ["Lange 1","Saxonia","Zeitwerk","Datograph","1815","Odysseus","Richard Lange","Tourbograph","Double Split","Triple Split","Lange 31","Cabaret"],
  "Jaeger-LeCoultre": ["Reverso","Master Control","Master Ultra Thin","Polaris","Rendez-Vous","Atmos","Master Grande Tradition","Master Compressor","Memovox","Geophysic","Duomètre","Gyrotourbillon","Hybris Mechanica","Hybris Artistica"],
  "Blancpain": ["Fifty Fathoms","Villeret","Le Brassus","L-evolution","Air Command","Bathyscaphe","Ladybird","Ultraplate"],
  "Breguet": ["Classique","Tradition","Marine","Reine de Naples","Type XX","Héritage"],
  "Glashütte Original": ["PanoMaticLunar","Senator Excellence","SeaQ","SeaQ Panorama Date","Senator Chronograph","PanoReserve","PanoInverse","Senator Cosmopolite","Senator Chronometer","PanoMaticInverse","PanoMaticDate","PanoGraph","Senator Perpetual Calendar","Senator Observer","Senator Tourbillon","PanoMaticCentral","PanoRetroGraph","Sixties","Seventies","Senator Diary","Alfred Helwig Tourbillon","Sport Evolution","Pavonina","Lady Serenade","Senator Karrée"],
  "H. Moser & Cie": ["Endeavour","Streamliner","Pioneer","Venturer","Heritage","Swiss Alp Watch"],
  "F.P. Journe": ["Chronomètre à Résonance","Tourbillon Souverain","Chronomètre Bleu","Chronomètre Souverain","Chronomètre Optimum","Octa Automatique","Octa Réserve de Marche","Octa Calendrier","Octa UTC","Octa Divine","Centigraphe Souverain","Répétition Souveraine","Sonnerie Souveraine","Astronomic Souveraine","Vagabondage","Élégante","lineSport"],
  "MB&F": ["Horological Machine N°3 (HM3)","Horological Machine N°6 (HM6)","Horological Machine N°9 (HM9)","Legacy Machine N°1 (LM1)","Legacy Machine Perpetual","Legacy Machine FlyingT","Legacy Machine Sequential","Legacy Machine Split Escapement","Legacy Machine Thunderdome","Horological Machine N°1 (HM1)","Horological Machine N°2 (HM2)","Horological Machine N°4 (HM4)","Horological Machine N°5 (HM5)","Horological Machine N°7 (HM7)","Horological Machine N°8 (HM8)","Horological Machine N°10 (HM10)","Horological Machine N°11 (HM11)","Horological Machine N°12 (HM12)","Legacy Machine N°2 (LM2)","Legacy Machine 101 (LM101)","HMX","Legacy Machine X (LMX)","M.A.D.1","M.A.D.2","MusicMachine"],
  "Roger Dubuis": ["Excalibur","Velvet","La Monégasque","Hommage","KingSquare","Pulsion","Golden Square","Much More","Too Much","Follow Me","Sympathie"],
  "Urwerk": ["UR-105","UR-110","UR-210","UR-100","UR-202","UR-103","EMC","UR-112","UR-111C","UR-220","UR-101","UR-102","UR-201","UR-203","UR-106","UR-120","UR-150","UR-230","UR-1001","UR-CC1","AMC"],
  "De Bethune": ["DB28","DB25","DB27","DB Kind of Two","Dream Watch","DB28XP","DB28XS","DB29 Maxichrono"],
  "Cartier": ["Tank","Santos","Ballon Bleu","Panthère","Pasha","Ronde de Cartier","Santos Dumont","Tank Louis Cartier","Tank Française","Tank Américaine","Tank Must","Tank Solo","Tank Asymétrique","Tortue","Baignoire","Tonneau","Crash","Cloche de Cartier","Drive de Cartier","Clé de Cartier","Calibre de Cartier","Rotonde de Cartier","Roadster","Cartier Privé"],
  "Omega": ["Speedmaster","Speedmaster Moonwatch","Seamaster","Seamaster Diver 300M","Seamaster Planet Ocean 600M","Seamaster Aqua Terra","Seamaster 300","Constellation","De Ville","De Ville Prestige","De Ville Trésor","De Ville Hour Vision","Globemaster","Railmaster","Speedmaster '57","Speedmaster Racing","Constellation Manhattan","Ladymatic"],
  "Tudor": ["Black Bay","Black Bay Fifty-Eight","Black Bay GMT","Black Bay Chrono","Black Bay Pro","Pelagos","Pelagos FXD","Ranger","North Flag","Royal","1926","Glamour","Style","Clair de Rose","Heritage Chrono","Heritage Advisor","Fastrider","Grantour","Monte Carlo","Prince","Hydronaut"],
  "IWC": ["Portugieser","Pilot's Watch","Portofino","Ingenieur","Aquatimer","Da Vinci","GST"],
  "Breitling": ["Navitimer","Chronomat","Superocean","Avenger","Premier","Superocean Heritage","Top Time","Aerospace","Emergency","Transocean","Endurance Pro","Super Chronomat","Colt","Galactic","Montbrillant","Cockpit","Chronospace","Exospace B55"],
  "Hublot": ["Big Bang","Classic Fusion","Spirit of Big Bang","King Power","Square Bang","Masterpiece (MP)"],
  "Tag Heuer": ["Carrera","Monaco","Aquaracer","Formula 1","Link","Autavia","Monza","Connected","Grand Carrera","Silverstone","Kirium","2000 Series","Alter Ego"],
  "Panerai": ["Luminor","Luminor Marina","Submersible","Radiomir","Luminor Due","Luminor 1950","Radiomir 1940"],
  "Chopard": ["Happy Sport","Alpine Eagle","Mille Miglia","L.U.C","Happy Diamonds","IMPERIALE","Ice Cube","Happy Hearts","Classic Racing","L'Heure du Diamant","La Strada","Two O Ten"],
  "Zenith": ["El Primero","Defy","Chronomaster","Pilot","Elite","Captain","Academy","Port Royal"],
  "Girard-Perregaux": ["Laureato","Tourbillon with Three Gold Bridges","1966","Vintage 1945","Cat's Eye","Casquette","Sea Hawk","WW.TC","Traveller","Neo Bridges","Free Bridge","Constant Escapement","Richeville"],
  "Franck Muller": ["Vanguard","Cintree Curvex","Casablanca","Crazy Hours","Long Island","Conquistador","Master of Complications","Color Dreams","Aeternitas","Giga Tourbillon","Vegas","Double Mystery","Mariner","Round","Imperial Tourbillon","Secret Hours"],
  "Harry Winston": ["Opus","Ocean","Premier","Midnight","Avenue","Histoire de Tourbillon","Project Z"],
  "Piaget": ["Altiplano","Polo","Limelight","Possession","Emperador","Black Tie","Gouverneur","Dancer","Miss Protocole","Upstream","Andy Warhol"],
  "Bvlgari": ["Octo Finissimo","Serpenti","Octo","Bvlgari Bvlgari","Lvcea","Octo Roma","Diagono","Aluminium","Assioma","Rettangolo","Ergon","Solotempo","Daniel Roth","Gerald Genta"],
  "Chanel": ["J12","Première","Boy·Friend","Monsieur","Coco Crush","Mademoiselle Privé","Code Coco","Camélia","1932"],
  "Dior": ["La D de Dior","Grand Bal","Gem Dior","Dior VIII","Dior Christal","Grand Soir","Chiffre Rouge"],
  "Louis Vuitton": ["Tambour","Escale","Tambour Horizon","Tambour Moon","Tambour Street Diver","Tambour Curve","Voyager","Spin Time","Tambour Convergence"],
  "Hermès": ["Arceau","Cape Cod","Heure H","Slim d'Hermès","H08","Cut","Dressage","Clipper","Kelly","Médor","Carré H","Galop d'Hermès","Nantucket","Tandem"],
  "Van Cleef & Arpels": ["Alhambra","Frivole","Perlée","Socrate","Cosmos","Lotus","Snowflake","Bouton d'Or","Cadenas","Ludo","Pierre Arpels","Lady Arpels","Poetic Complications","Midnight in Paris","Pont des Amoureux","Midnight Planetarium","Lady Arpels Planetarium","Charms Extraordinaires","Poetic Wish","Fée Ondine","Papillon Automate","Ballerina","Ballerina Féerique","Jour Nuit"],
  "Graff": ["MasterGraff","GyroGraff","GraffStar","ChronoGraff","ScubaGraff","Princess Butterfly","Disco Butterfly","Classic Butterfly","Spiral","Graff Vendôme","Tilda's Bow","Unique Timepieces"],
  "Ulysse Nardin": ["Freak","Marine","Diver","Blast","Classico","Executive","Marine Torpilleur","Marine Chronometer","Perpetual Ludwig","Sonata","San Marco","Michelangelo","Astrolabium Galileo Galilei","Planetarium Copernicus","Tellurium Johannes Kepler","Jade","Quadrato","Hourstriker"],
  "Parmigiani Fleurier": ["Tonda","Toric","Kalpa","Ovale","Pershing","Bugatti","Transforma"],
  "Bell & Ross": ["BR 03","BR 01","BR 05","BR V2","BR 02","BR V3","BR S","BR X1","BR X5","BR X2"],
  "Oris": ["Aquis","Divers Sixty-Five","ProPilot","Big Crown","Big Crown Pointer Date","Artelier","Chronoris","Williams","Aquis Date","Artix","Regulateur","Worldtimer","Hölstein Edition","BC3","BC4","TT1","TT2"],
  "Rado": ["Captain Cook","DiaStar","True","HyperChrome","Centrix","Coupole","Integral","DiaMaster","Anatom","DiaStar Original","Sintra","True Square","True Thinline","Esenza","Specchio","Silverstone","V10K"],
  "Grand Seiko": ["Heritage Collection","Elegance Collection","Sport Collection","Evolution 9 Collection","Spring Drive","Hi-Beat 36000","Snowflake","White Birch","Tentagraph"],
  "Seiko": ["Prospex","Presage","Seiko 5 Sports","Grand Seiko","Astron","Credor","Seiko 5","Alpinist","King Seiko","SKX","Lukia","Brightz","Sportura","Velatura","Arctura","Kinetic","Dolce","Exceline","Lassale","Giugiaro"],
  "Citizen": ["Eco-Drive","Promaster","The Citizen","Series 8","Tsuyosa","Attesa","Campanola","Satellite Wave","Nighthawk","Skyhawk","Navihawk","Tsuno Chrono Racer","Perpetual Chrono A-T","Super Titanium","Record Label","Exceed","Citizen L","xC","Star Wars"],
  "Longines": ["Master Collection","HydroConquest","Conquest","Spirit","Legend Diver","Heritage","DolceVita","La Grande Classique","Record","Flagship","Presence","Elegant Collection","Ultra-Chron","Lindbergh Hour Angle","PrimaLuna","Evidenza","Admiral","BelleArte","Equestrian","Symphonette"],
  "Tissot": ["PRX","Seastar","T-Race","Le Locle","Gentleman","T-Touch","PRC 200","Chemin des Tourelles","Everytime","Visodate","Heritage","Couturier","Carson","PR 100","PRS 516","Supersport","Tradition","Classic Dream","Ballade","Bridgeport","T-Complication","Rock Watch"],
  "Hamilton": ["Khaki Field","Khaki Aviation","Khaki Navy","Jazzmaster","Ventura","American Classic","Broadway","Intra-Matic","PSR","Khaki X-Wind","Khaki BeLOWZERO","Pan Europ","Boulton","Ardmore","Spirit of Liberty","Pulsomatic","Thin-o-Matic"],
  "Frederique Constant": ["Classics","Slimline","Highlife","Manufacture","Heart Beat","Runabout","Vintage Rally","Yacht Timer","Smartwatch (Horological Smartwatch)","Persuasion","Carrée"],
  "Mido": ["Ocean Star","Multifort","Commander","Baroncelli","Belluna","All Dial","Bruner","Rainflower","Great Wall"],
  "Alpina": ["Alpiner","Startimer Pilot","Seastrong Diver","Alpiner Extreme","Seastrong Diver 300","Comtesse","AlpinerX","Startimer Pilot Heritage","Seastrong Diver Heritage","Alpiner Regulator","Startimer Pilot Worldtimer","Sailing Yacht Timer"]
};
